const STORAGE_KEY = 'gad_love_calculator_data_v4';
const PASSWORD_KEY = 'gad_admin_password';
function getAdminPassword() { const stored = localStorage.getItem(PASSWORD_KEY); return stored || '@mawuedonuse$7'; }
function getSubmissions() { try { const data = localStorage.getItem(STORAGE_KEY); return data ? JSON.parse(data) : []; } catch (e) { return []; } }
function saveSubmission(name, love) { const submissions = getSubmissions(); submissions.unshift({ name: name.trim(), love: love.trim(), time: new Date().toLocaleString(), id: Date.now() }); localStorage.setItem(STORAGE_KEY, JSON.stringify(submissions)); }
function deleteOne(index) { const submissions = getSubmissions(); submissions.splice(index, 1); localStorage.setItem(STORAGE_KEY, JSON.stringify(submissions)); renderAdminTable(); }
function switchPage(pageId) { document.querySelectorAll('.page').forEach(p => { p.classList.remove('active'); p.style.display = 'none'; }); const target = document.getElementById(pageId); if (target) { target.style.display = 'flex'; setTimeout(() => { target.classList.add('active'); }, 10); } window.scrollTo(0, 0); }
function goBack() { document.getElementById('userName').value = ''; document.getElementById('loveName').value = ''; switchPage('page1'); }
function handleCalculate() { const userName = document.getElementById('userName').value; const loveName = document.getElementById('loveName').value; if (!userName.trim() || !loveName.trim()) { alert('Please enter both names! 💕'); return; } saveSubmission(userName, loveName); switchPage('page2'); }
function renderAdminTable() { const tbody = document.getElementById('adminTableBody'); const submissions = getSubmissions(); const badge = document.getElementById('countBadge'); badge.textContent = submissions.length; if (submissions.length === 0) { tbody.innerHTML = '<tr><td colspan="2" class="empty-msg">No submissions yet... Go share your link! 😏</td></tr>'; return; } tbody.innerHTML = submissions.map((sub, index) => `<tr><td>${escapeHtml(sub.name)}</td><td>${escapeHtml(sub.love)} <button class="delete-btn" onclick="deleteOne(${index})" title="Delete this">×</button></td></tr>`).join(''); }
function escapeHtml(text) { const div = document.createElement('div'); div.textContent = text; return div.innerHTML; }
function checkPassword() { const input = document.getElementById('adminPassword').value.trim(); const error = document.getElementById('loginError'); if (input === getAdminPassword()) { document.getElementById('loginOverlay').style.display = 'none'; document.getElementById('adminPassword').value = ''; renderAdminTable(); } else { error.style.display = 'block'; setTimeout(() => { error.style.display = 'none'; }, 3000); } }
function changePassword() { const oldPass = document.getElementById('oldPassword').value.trim(); const newPass = document.getElementById('newPassword').value.trim(); const msg = document.getElementById('passwordMsg'); if (!oldPass || !newPass) { msg.textContent = 'Please fill both fields!'; msg.className = 'password-msg error'; return; } if (oldPass !== getAdminPassword()) { msg.textContent = 'Current password is wrong!'; msg.className = 'password-msg error'; return; } if (newPass.length < 4) { msg.textContent = 'New password must be at least 4 characters!'; msg.className = 'password-msg error'; return; } localStorage.setItem(PASSWORD_KEY, newPass); msg.textContent = 'Password changed successfully! ✅'; msg.className = 'password-msg success'; document.getElementById('oldPassword').value = ''; document.getElementById('newPassword').value = ''; setTimeout(() => { msg.textContent = ''; }, 3000); }
function checkUrlHash() { if (window.location.hash === '#admin') { document.getElementById('loginOverlay').style.display = 'flex'; switchPage('page3'); } }
document.addEventListener('DOMContentLoaded', function() { document.getElementById('calcBtn').addEventListener('click', handleCalculate); document.getElementById('backBtn1').addEventListener('click', goBack); document.getElementById('backBtn2').addEventListener('click', goBack); document.getElementById('loginBtn').addEventListener('click', checkPassword); document.getElementById('changePassBtn').addEventListener('click', changePassword); document.getElementById('adminPassword').addEventListener('keypress', function(e) { if (e.key === 'Enter') checkPassword(); }); document.getElementById('loveName').addEventListener('keypress', function(e) { if (e.key === 'Enter') handleCalculate(); }); checkUrlHash(); });
window.addEventListener('hashchange', checkUrlHash);